// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///  options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_st-m3X9z0UwWlqP6A6QsXUSAR4hoOEU',
    appId: '1:1041322446590:web:d0066f33629097b65f1faf',
    messagingSenderId: '1041322446590',
    projectId: 'studio-mf-57238',
    authDomain: 'studio-mf-57238.firebaseapp.com',
    storageBucket: 'studio-mf-57238.appspot.com',
    measurementId: 'G-4EB3B6PZ31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xbgh0_23feG42EDD9CJ-hxFdycLPbgo',
    appId: '1:1041322446590:android:94189f5bd812274e5f1faf',
    messagingSenderId: '1041322446590',
    projectId: 'studio-mf-57238',
    storageBucket: 'studio-mf-57238.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgnvCt75U1pD_xIOSJ6_LrDrjvN1qTiVQ',
    appId: '1:1041322446590:ios:757eb0ff8bbbaa765f1faf',
    messagingSenderId: '1041322446590',
    projectId: 'studio-mf-57238',
    storageBucket: 'studio-mf-57238.appspot.com',
    iosBundleId: 'com.example.pruebaIntegradora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgnvCt75U1pD_xIOSJ6_LrDrjvN1qTiVQ',
    appId: '1:1041322446590:ios:757eb0ff8bbbaa765f1faf',
    messagingSenderId: '1041322446590',
    projectId: 'studio-mf-57238',
    storageBucket: 'studio-mf-57238.appspot.com',
    iosBundleId: 'com.example.pruebaIntegradora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_st-m3X9z0UwWlqP6A6QsXUSAR4hoOEU',
    appId: '1:1041322446590:web:e929f80fffdd11585f1faf',
    messagingSenderId: '1041322446590',
    projectId: 'studio-mf-57238',
    authDomain: 'studio-mf-57238.firebaseapp.com',
    storageBucket: 'studio-mf-57238.appspot.com',
    measurementId: 'G-PCXPHRBL4S',
  );
}
